import { Person } from "../models/types";

export const PERSON_MOCK_DATA:Person[] = [
    {
        "id": 35089,
        "personId": 3038,
        "nameRu": "Аджай Найду",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/3038.jpg",
        "birthday": "1972-02-12",
        "death": null,
        "age": 50,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "0",
        "profession": "Актер, Режиссер, Сценарист"
    },
    {
        "id": 7790,
        "personId": 6652,
        "nameRu": "Джефф Бриджес",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/6652.jpg",
        "birthday": "1949-12-04",
        "death": null,
        "age": 72,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "1",
        "profession": "Актер, Продюсер"
    },
    {
        "id": 25594,
        "personId": 17476,
        "nameRu": "Дэвид Патрик Келли",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/17476.jpg",
        "birthday": "1951-01-23",
        "death": null,
        "age": 71,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "0",
        "profession": "Актер"
    },
    {
        "id": 75467,
        "personId": 50720,
        "nameRu": "Иэн Софтли",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/50720.jpg",
        "birthday": "1956-10-30",
        "death": null,
        "age": 65,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "1",
        "profession": "Режиссер, Продюсер, Сценарист"
    },
    {
        "id": 18528,
        "personId": 11380,
        "nameRu": "Кевин Спейси",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/11380.jpg",
        "birthday": "1959-07-26",
        "death": null,
        "age": 62,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "1",
        "profession": "Актер, Продюсер, Режиссер"
    },
    {
        "id": 65148,
        "personId": 2673,
        "nameRu": "Мэри МакКормак",
        "nameEng": null,
        "sex": "FEMALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/2673.jpg",
        "birthday": "1969-02-08",
        "death": null,
        "age": 53,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "1",
        "profession": "Актриса, Продюсер, Сценарист"
    },
    {
        "id": 64513,
        "personId": 8394,
        "nameRu": "Питер Герети",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/8394.jpg",
        "birthday": "1940-05-17",
        "death": null,
        "age": 81,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "0",
        "profession": "Актер"
    },
    {
        "id": 36181,
        "personId": 11766,
        "nameRu": "Селия Уэстон",
        "nameEng": null,
        "sex": "FEMALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/11766.jpg",
        "birthday": "1951-12-14",
        "death": null,
        "age": 70,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "1",
        "profession": "Актриса"
    },
    {
        "id": 75468,
        "personId": 50723,
        "nameRu": "Сол Уильямс",
        "nameEng": null,
        "sex": "MALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/50723.jpg",
        "birthday": "1972-03-01",
        "death": null,
        "age": 50,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "0",
        "profession": "Актер, Сценарист, Композитор"
    },
    {
        "id": 30414,
        "personId": 8293,
        "nameRu": "Элфри Вудард",
        "nameEng": null,
        "sex": "FEMALE",
        "posterUrl": "https://kinopoiskapiunofficial.tech/images/actor_posters/kp/8293.jpg",
        "birthday": "1952-11-08",
        "death": null,
        "age": 69,
        "birthPlace": null,
        "deathPlace": null,
        "hasAwards": "1",
        "profession": "Актриса, Продюсер"
    }
]