export const CLIENT_GENRE_LIST = {
    crime: 1,
    comedy:  2, 
    detective: 3, 
    drama:  4, 
    military: 5, 
    story: 6,
    melodrama:7,
    action:  8, 
    thriller:  9, 
    biography:  10, 
    family:  11, 
    fantastic:  12, 
    adventures:  13, 
    fantasy:  14, 
    cartoon: 15, 
    horror:  16, 
    kids:  17, 
    western:  18, 
    musical:  19, 
    music:  20, 
    sport:  21, 
    shortfilm:  22, 
    anime:  23, 
    documentary:  24, 
    filmnoir:  25, 
    realtv:  26, 
}